cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.get_product_list, name='product_list'),
    path('search_product/', views.search_product, name='search'),
    path('add-product/', views.create_product, name='add_product'),
    path('delete/<str:product_slug>/', views.delete_product, name='delete_product'),
    path('<str:category_slug>/', views.get_product_list, name='product_list_by_category'),
    path('products/<str:product_slug>/', views.get_product_detail, name='product_details'),

]
# http://127.0.0.1:8000/products/1/lenovo/

cart/models.py
from django.db import models

# Create your models here.

order/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    """http://localhost:8000/category/computers/
    """
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        # http://test/object111/
        return reverse('shop:product_list_by_category',
                       args=[self.slug, ])


class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name='products', on_delete=models.CASCADE
    )
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveSmallIntegerField(default=0)
    available = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        # http://test/object111/
        return reverse('shop:product_details',
                       args=[self.slug, ])

    def save(self):
        self.slug = self.name.lower().replace(" ", '-')
        return super().save()

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [
    (i, str(i)) for i in range(1, 21)
]
# PRODUCT_QUANTITY_CHOICES = [
#     (1, 1),
#     (2, 2),
#     (3, 3)
# ]
# dict(PRODUCT_QUANTITY_CHOICES)
# {1:1, 2:2, 3:3}
# [
# (i, i), (i, i)
# ]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES
    )
    update = forms.BooleanField(
        required=False, widget=forms.HiddenInput
    )

shop/forms.py
from django.forms import ModelForm, ValidationError
from .models import Product


class ProductForm(ModelForm):
    class Meta:
        model = Product
        exclude = ('created_at', 'updated_at', 'slug')

    def clean(self):
        slug = self.cleaned_data.get('name').lower().replace(" ", '-')
        if Product.objects.filter(slug=slug).exists():
            raise ValidationError('Product with such name already exists!')
        return self.cleaned_data

cart/views.py
from django.shortcuts import (
    render,
    get_object_or_404,
    redirect
)
from django.views.decorators.http import require_http_methods

from cart.forms import CartAddProductForm
from cart.helpers import Cart
from shop.models import Product


@require_http_methods(['POST'])
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cleaned_data = form.cleaned_data
        cart.add_or_update(
            product=product,
            quantity=cleaned_data['quantity'],
            update_quantity=cleaned_data['update']
        )
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request,
                  'cart_detail.html',
                  {'cart': cart}
                  )

order/views.py
from django.shortcuts import render

# Create your views here.

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.db.models import Q
from django.conf import settings

from cart.forms import CartAddProductForm
from .forms import ProductForm
from .helpers import product_list_filter_sort
from .models import Category, Product


def search_product(request):
    category = None
    categories = Category.objects.all()
    products = None
    search = request.GET.get('search')
    if search:
        products = Product.objects.filter(Q(name__icontains=search) |
                                          Q(description__icontains=search)
                                          )
    context = {
        'products': products,
        'categories': categories,
        'category': category
    }
    return render(
        request,
        'product/product_list.html',
        context
    )


def get_product_list(request, category_slug=None):
    """Функция вытаскивает продукты и если слаг приходит заполненым
    то фильтрует по слагу и в конце возвращаем контексты
    """

    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True).order_by('-created_at')
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    # фильтрацию по прайс и по категориям
    products = product_list_filter_sort(
        request,
        products,
        category_slug
    )

    paginator = Paginator(products, settings.PAGINATOR_NUM)
    page_number = request.GET.get('page')
    products = paginator.get_page(page_number)

    context = {
        'products': products,
        'categories': categories,
        'category': category,
    }
    return render(
        request,
        'product/product_list.html',
        context
    )


def get_product_detail(request, product_slug):
    """Детализация продукта
    """
    product = get_object_or_404(Product, slug=product_slug)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }
    return render(
        request, 'product/product_detail.html', context
    )


def create_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            # product = Product.objects.create(**form.cleaned_data)
            return redirect(product.get_absolute_url())
    else:
        form = ProductForm()

    return render(request, 'product/create_product.html', {'product_form': form})


def delete_product(request, product_slug):
    Product.objects.get(slug=product_slug).delete()
    return redirect('/')

cart/templates/cart_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}
    <h1>Your shopping cart</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static 'img/no_image.png' %}
                                {% endif %}">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url 'cart:cart_remove' product.id%}">Remove</a></td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'shop:product_list' %}" class="button light">Continue shopping</a>
        <a href="#" class="button">Checkout</a>
    </p>
{% endblock %}

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}My shop{% endblock title %}</title>
   <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"/>
</head>
<body>
<nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
        <a href="/" class="navbar-brand">My shop</a>
        <a href="/add-product"><i class="fa-duotone fa-plus"></i></a>
        <form class="d-flex" action="{% url 'shop:search' %}">
            <input class="form-control me-2" name="search" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    </div>
</nav>
<div id="content">
    {% block content %}
        Empty Content
    {% endblock content %}
</div>
{% if products %}
<div class="pagination">
    <span class="step-links">
        {% if products.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ products.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ products.number }} of {{ products.paginator.num_pages }}.
        </span>

        {% if products.has_next %}
            <a href="?page={{ products.next_page_number }}">next</a>
            <a href="?page={{ products.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endif %}
</body>
</html>

shop/templates/product/create_product.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ product_form.as_p }}
        <button type="submit" class="btn btn-secondary">Create</button>
    </form>
{% endblock %}

shop/templates/product/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}
  <div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
    <h1>{{ product.name }}</h1>
    <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
    <p class="price">${{ product.price }}</p>
    {{ product.description|linebreaks }}

    <form action="{% url 'cart:cart_add' product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Add to cart">
    </form>

  <div class="d-flex justify-content-between total font-weight-bold mt-4">
      <button type="button" class="btn btn-success">Update</button>
      <a href="{% url 'shop:delete_product' product.slug %}"><button type="button" class="btn btn-danger">Delete</button></a>
  </div>
  </div>

{% endblock %}

shop/templates/product/product_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar">
    <h3>Categories</h3>
    <a href="{% url 'shop:product_list' %}?-price=sort">
      <button>Expensive </button></a>
    <a href="{% url 'shop:product_list' %}?price=sort">
      <button>Low</button>
    </a>
    <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url 'shop:product_list' %}">All</a>
      </li>
      {% for cat in categories %}
        <li {% if category.slug == cat.slug %}class="selected"{% endif %}>
          <a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
    <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
  <div id="main" class="product-list">
    {% for product in products %}
      <div class="item">
        <a href="{{ product.get_absolute_url }}">
          <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
        </a>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
        ${{ product.price }}
      </div>
    {% endfor %}
  </div>


{% endblock %}